### ISSUE TITLE
Repurpose "Description" field on Layouts for the icon

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10684]
So we have an issue with the new UI where if you have any custom "CMS Tab" it will not show an icon.  Good news is that in 4.0 we are no longer using the description field.  We need to repurpose the description field to allow a user to specify an icon or a font-awesome character that the user would want to use as the representative icon.  

We can allow a user to type in an icon style from the font awesome CSS:

http://fontawesome.io/cheatsheet/

- When the user enters the class name, we need to display the icon on the right of the text box 
- We need to sanitize the data as UTF-8 and javascript safe.
- let's cut and paste the list of available icons onto a doc on our doc site.

![screen shot 2017-02-09 at 4 02 05 pm](https://cloud.githubusercontent.com/assets/934364/22803486/2877a514-eee3-11e6-8357-cf0fabd55a70.png)

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/268 and https://github.com/dotCMS/core/pull/10726

**Comment by oswaldogallango** [comment]
update font-awesome css in angular P.R https://github.com/dotCMS/core-web/pull/269

**Comment by john-thomas-dotcms** [comment]
@wezell, with regards to the doc, there are alot of icons in font-awesome to list them all :).

How about we create a subset of icons which might be used commonly, and refer users to the cheatsheet in the docs in case they want more?

**Comment by oswaldogallango** [comment]
P.R setting default icon https://github.com/dotCMS/core-web/pull/270

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // Chrome.... New issue reported here #10743

**Comment by jgambarios** [comment]
Moved to a new iteration just because we are still missing the documentation here.

**Comment by john-thomas-dotcms** [comment]
Translation already completed
