### ISSUE TITLE
Problems loading the portlets after refresh the browser on FF and Safari

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10789]
We are unable to refresh the page, the system is not loading fine the portlet and leave a blank page 

## Expected Behavior
We should be able to refresh the browser and loading the portlet again 

## Current Behavior
We are unable to refresh the page because leave the portlet in blank

## Steps to Reproduce (for bugs)
1. Login 
2. Go to any portlet 
3. Refresh the browser 

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jcastro-dotcms** [comment]
I tested refreshing the browser (Chrome) in several portlets and cannot reproduce any problem.

**Comment by bryanboza** [comment]
Yes, this because you are in Chrome, I am unable to reproduce on chrome...

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/10770

**Comment by bryanboza** [comment]
Still having problems with the angular portlets (rules).... When you refresh the browser system isn't loading the same portlet again
