### ISSUE TITLE
Categories portlet isn't loading on master-4.1

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11140]
## Expected Behavior
We should be able to access any portlet without problems 

## Current Behavior
The categories portlet isn't loading, we have no errors in the logs... 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Try to navigate to types & tags --> categories 

## Your Environment
Tested on  master-4.1 // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11220

**Comment by jgambarios** [comment]
**Note to QA:** After this fix the portlet loads but there are not Breadcrumbs for categories, the Breadcrumbs are been added in https://github.com/dotCMS/core/issues/11221

**Comment by bryanboza** [comment]
Now this portlet is loading, but we still having problems in the category permissions tab 
SC: https://screencast.com/t/U6vjXiQB

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/11221

**Comment by bryanboza** [comment]
Still having problems trying to open the permissions tab... Here the log: https://gist.github.com/bryanboza/faa4f5101a476fbda75fbecdda507a3f

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11399

**Comment by bryanboza** [comment]
Fixed, tested in the last master-4.1
