### ISSUE TITLE
Permissions checkboxes not properly aligned

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12835]
See:

<img width="1698" alt="2017-10-11_1358" src="https://user-images.githubusercontent.com/1576794/31463856-2035a302-ae95-11e7-8069-66a9a0008e84.png">

This is probably a leftover after converting Vanity URLs to content.

Reproduced in Master

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12839

**Comment by bryanboza** [comment]
Fixed, tested in the last master, and now looks as expected

**Comment by joseorsini** [comment]
Please reopen. Issues persist on dotCMS 4.2.2 

<img width="1673" alt="screen shot 2017-12-04 at 10 50 22 am" src="https://user-images.githubusercontent.com/1717110/33564796-065917b8-d8e1-11e7-9b46-0d211b053192.png">

As reported by customer https://dotcms.zendesk.com/agent/tickets/94875
