### ISSUE TITLE
Limited User can't create New Content Types

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15285]
Tested on latest 5.0.1 release on multiple servers, including demo.

To recreate bug:
1) Create a new blank site
2) Create a new role and give it full permissions over that site

<img width="1729" alt="screen shot 2018-09-13 at 5 32 20 pm" src="https://user-images.githubusercontent.com/1569167/45521398-0060bb80-b77b-11e8-8229-69083d893d36.png">

3) give the role access to the Content Types tool
4) create a new user, assign the user the role, and try to create a new content type, which exposed the bug

You must create a new site... the case will work if you give the permissions to the starter demo site.

video: https://www.screencast.com/t/hEIh25pwIwBB

**Comment by DeanGonzalez** [comment]
We need to make sure a unit test for this to make sure limited users can create Content Types on non-starter hosts if given the right permissions.

**Comment by erickgonzalez** [comment]
Both issues have been fixed and this is working as it should now.

**Comment by bryanboza** [comment]
Tested in the last master and I still having the same problems here, please check this again

**Comment by bryanboza** [comment]
Seems the problem is because we are not updating the site selector when you login as.

**Comment by erickgonzalez** [comment]
Still waiting to this ticket #15304

**Comment by bryanboza** [comment]
We are having some permissions problems here: 

- If you create a new site and set this permissions 
<img width="1423" alt="edit1" src="https://user-images.githubusercontent.com/2641437/49041450-e08e4080-f18a-11e8-8326-a662d69f48ab.png">
We are allowing the user to create new content types, but if you try to add//remove fields we have an 403 error. This because to create new content types, we are just validating the `add children` and `publish` permissions. But to add//remove fields you need to have the maximum level of permissions `edit permissions`.

Then I think don't make sense allow the user create new content types, if they can't use it. We need to validate the same permissions to create and edit content types.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15645

**Comment by erickgonzalez** [comment]
After discussing with @fmontes is a UI issue, so a new issue has been created https://github.com/dotCMS/core/issues/15707

**Comment by bryanboza** [comment]
Fixed, tested after the fix #15707 and now it is working as expected
