### ISSUE TITLE
DotCMS can't run Task04360WorkflowSchemeDropUniqueNameConstraint with MS SQL

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#16518]
### Describe the bug
A dotCMS upgrade from 4.3.3 to 5.1.1 failed because Task04360 couldn't be executed. The error is: java.sql.SQLException: 'unique_workflow_scheme_name' is not a constraint. The problem is that unique_workflow_scheme_name is not a constraint but an index. Maybe it's a MS SQL thing?

### Desktop (please complete the following information):
- OS: Windows
- DotCMS version: 4.3.3 to 5.1.1
- Database: MS SQL

### Workaround
I manually removed the index unique_workflow_scheme_name index and set the db_version to 4360.

**Comment by wezell** [comment]
This is resolved in 5.1.5

**Comment by Xander-Steinmann** [comment]
I still have this issue when upgrading from 4.3.3 to 5.1.5 on Windows with MS SQL

**Comment by Xander-Steinmann** [comment]
I think the query should be "Drop index unique_workflow_scheme_name on workflow_scheme"
