### ISSUE TITLE
Untranslated language variables (message keys) in dotCMS Admin Interface

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#16584]
### Describe the bug
Some message keys in the dotCMS Admin Interface are not translated, when selecting a different admin backend language than the existing frontend languages.

### Steps to reproduce the behavior:
1. Go to demo.dotcms.com/dotAdmin
2. Select a different language than English or Spanish and log in to the admin interface
3. Go to Types & Tags > Content Types
4. See untranslated language variables (message keys)
5. Go to Types & Tags > Languages
6. Add the language which has been selected for the current admin user
7. Again go to Types & Tags > Content Types
8. See all language variables translated 

### Expected behavior
All language variables should be translated correctly, no matter which language has been selected for the admin interface and no matter which frontend languages have been added to (or removed from) the system. The backend languages should be completely independent from the frontend languages.

### Screenshots
Find attached two screenshots with highlighted message keys that have not been translated.

![dotcms_content_types](https://user-images.githubusercontent.com/11347836/57777691-b6bddb80-7722-11e9-878a-f3062d71bc3a.png)

![dotcms_edit_contentlet](https://user-images.githubusercontent.com/11347836/57777714-c3423400-7722-11e9-8ce7-59bfe44e4189.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

### Additional context
It looks as if only the Angular language variables are not translated (all messages pulled from /api/v1/languages/i18n).

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
PR: #16616

**Comment by bryanboza** [comment]
Tested on master and we continue showing with some variables without translation... Tested with Deutsch

**Comment by wezell** [comment]
@bryanboza i18n only seems to be working if you have the language set up in the backend.  So, for example, if you change the login page to chinese, you do not see the chinese characters

**Comment by jgambarios** [comment]
Cherrypicked commit https://github.com/dotCMS/core/commit/2dfd2ae3e7259942eab3d837515a6061e7031c30 in `release-5.1.6`

**Comment by bryanboza** [comment]
We need to add the translations, we still showing the English keys 
https://screencast.com/t/jaa8MB69

**Comment by wezell** [comment]
@bryanboza for all languages or just chinese?

**Comment by dsilvam** [comment]
PR master: https://github.com/dotCMS/core/pull/16661

**Comment by bryanboza** [comment]
Fixed tested after the merge and now we have the translation for those keys

**Comment by erickgonzalez** [comment]
Still having the same issue, the language variables keys are shown until you add the language. You can see this on the login page and on the Content Types portlet.

**Before Adding the Language**

![image](https://user-images.githubusercontent.com/5278970/59123925-a1039680-891b-11e9-9b0c-67931bfdf574.png)

![image](https://user-images.githubusercontent.com/5278970/59124264-7cf48500-891c-11e9-9224-f7d9f5e04c15.png)

![image](https://user-images.githubusercontent.com/5278970/59123969-b973b100-891b-11e9-8271-39cb8f28dbac.png)


**After Adding the Language**

![image](https://user-images.githubusercontent.com/5278970/59124149-2e46eb00-891c-11e9-9a85-19f766266111.png)

![image](https://user-images.githubusercontent.com/5278970/59124158-369f2600-891c-11e9-9ac3-620f0b038e93.png)

![image](https://user-images.githubusercontent.com/5278970/59124169-3bfc7080-891c-11e9-9959-9b7ddf1dabb6.png)

**Comment by dsilvam** [comment]
PR master: https://github.com/dotCMS/core/pull/16655

**Comment by erickgonzalez** [comment]
After the last changes, it's working as it should.

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF... New UI enhancements will be worked in a separate card
