### ISSUE TITLE
Personalization BE issues

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16977]
- When you copy a personalized page, we are not including the personalizations, and we are adding all the content of those to the default view. The same case when you copy and paste
SC: https://screencast.com/t/AYXAGLyJl

- We are not sending the personalization version via Push Publish. If you send a page with some versions with personalization, in the receiver side we are unable to show those versions.  
_We show the content of those versions, but not the personalized version._ 

- We need to clear cache after editing some persona. If you edit the persona key, we still showing the personalized version of the pages for this persona, but those are blank pages, we lost the content. This until you clear the cache
SC: https://screencast.com/t/HFzlrvrjLqUe

- If you create a new persona content type and add a new persona for this content type. If you create a new personalized version of some page for this persona, when you push the page, we are not sending the content type, neither the persona by dependencies

**Comment by wezell** [comment]
@bryanboza Please retest

**Comment by bryanboza** [comment]
The 3 cases still happening

**Comment by wezell** [comment]
PR: #17311
PR: dotCMS/enterprise-2.x#685

**Comment by fmontes** [comment]
- Error in logs when you have a multi-language page personalized and go to default visitor in any other language different to the default, we are having multiple lines with this errorr: 
```
12:08:07.483  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
12:08:07.484  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
12:08:07.484  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
12:08:07.486  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
12:08:07.487  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
12:08:07.488  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
12:08:07.489  ERROR business.VisitorAPIImpl - Can't find contentlet: modes.persona.no.persona lang:1 live:false
```

**Comment by jgambarios** [comment]
**Note to QA:** The issue described above by @fmontes was fixed in https://github.com/dotCMS/core/issues/17320
The Persons cache issue will be fix in https://github.com/dotCMS/core/issues/16697#issuecomment-523131916

**Comment by bryanboza** [comment]
We need some work here: 
- When you copy any page with a personalized version we still showing all the contents in the default visitor.
SC: https://screencast.com/t/vQbpGrqfz

- If you create a personalized version of the page, but don't publish this version, just leave the personalized version unpublished we are not sending it 

- If you create a new persona content type and add a new persona for this content type. If you create a new personalized version of some page for this persona, when you push the page, we are not sending the content type, neither the persona by dependencies

- We are not updating personas by dependency. If you create a new persona and push it, then you edit the persona Keytag on sender, create a new version for any page associated to this persona and push, we are not able to update the persona on the receiver side; And just don't show the personalized version

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17415

**Comment by bryanboza** [comment]
Fixed, tested on master and now the copy works as expected
