### ISSUE TITLE
Content Type Variable Assign should be case insensitive

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17051]
From the UI, it is possible to create a content type that has the same variable name as another - in a difference case.  Velocity variable names should be unique  (case insensitive).

### To reproduce
1. Add a new content type called "Web Page Content".  You will now have two content types, one with the variable `WebPageContent` and the old one with the variable `webPageContent`.

Needs Test

**Comment by nollymar** [comment]
Fixed on https://github.com/dotCMS/core/pull/17066

**Comment by erickgonzalez** [comment]
Needs work: Still having the issue, you shouldn't be able to have a content type with the same variable name regardless the case (e.g. `persona` and `PERSONA` is not allowed). Also the `contenttypeapi.find()` should be case insensitive.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17293

Note: `contenttypeapi.find()` method was already case insensitive. No change was needed here

**Comment by erickgonzalez** [comment]
Working as it should, now when you create a new content type is case insensitive, so if already exists is gonna add a number at the end. 
E.g
Persona -> Persona
PERSONA -> PERSONA1

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
