### ISSUE TITLE
Self Joined Relationship returning all values

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17477]
We are using new relationship fields. We have a content type called collection.
What we need is a parent-child relationship between collections.
I create relationship one-to-many and add two fields: parentCollection and childrenCollections.
In dotCMS admin console, everything looks OK. I can relate parent and/or children. Everything is as expected.
But REST api returns something else. Example:
I have collection B.
B.parentCollection = [A]
B.childrenCollections = [C, D]

REST call 
```
/api/content/depth/0/id/<collection id of B>:
{
....
parentCollections = [A, C, D]
....
}
```
There is no childrenCollections in the result JSON.
And all relations were merged into one.

**Comment by nollymar** [comment]
Fixed. https://github.com/dotCMS/core/pull/17488

**Note to QA:** Please test with different `depth` levels and both JSON and XML response

**Comment by erickgonzalez** [comment]
Tested via REST API using postman and new relationships fields return data were it belongs.

Test:
Created a CT **Movie** with a couple of relationships fields (self-related) and added content to both of them, after that called the endpoint and returned the correct values on each field.
```
"prequel": [
                "c1f4c1bb-b0c0-48f7-926d-c4283871f981",
                "6af9e90c-2f56-4996-882a-a4e9c3be9465"
            ],
"sequel": [
                "c71a8e43-7792-4cfd-936a-ce57162b3f6b"
            ]
```

**Comment by wezell** [comment]
We are saving the postman scripts as tests, right?  I am asking because we are going to need to add another travis test to test the apis via postman scripts

**Comment by erickgonzalez** [comment]
@wezell I have the postman queries I used locally but don't understand what you mean, here are the queries:
```
http://localhost:8080/api/content/depth/0/language/1/live/true/id/c1f4c1bb-b0c0-48f7-926d-c4283871f981
http://localhost:8080/api/content/depth/1/language/1/live/true/id/c1f4c1bb-b0c0-48f7-926d-c4283871f981
http://localhost:8080/api/content/depth/0/language/1/live/false/id/c1f4c1bb-b0c0-48f7-926d-c4283871f981
http://localhost:8080/api/content/depth/0/language/1/live/true/id/e208deac-4d51-4315-8211-4f36f1a8bbe7
http://localhost:8080/api/content/depth/2/language/1/live/false/id/e208deac-4d51-4315-8211-4f36f1a8bbe7
http://localhost:8080/api/content/depth/2/language/1/live/true/id/e208deac-4d51-4315-8211-4f36f1a8bbe7
```
All of them was tested against a CT that I created with several relationships (self joined and to other CT's)

**Comment by bryanboza** [comment]
We need some work here: 

After the test in the release branch, now when you have a self-related content type and the piece of content is related to more that one content, we show the relationship without problems at UI level, but when you try to get this via REST, we are getting just one related one and ignore the other ones 
Here is the content in the UI: 
![image](https://user-images.githubusercontent.com/2641437/67521095-68185400-f667-11e9-81e8-96f0dbd2d7f4.png)

And when you try to get the content via REST, we are returning just one related content 
![image](https://user-images.githubusercontent.com/2641437/67521337-ec6ad700-f667-11e9-997d-3c3b3dabaa0d.png)

**Comment by nollymar** [comment]
@bryanboza this occurs when you create two independent self-relationships (two one sided self-relationships), not exactly the case fixed on this issue (one self-relationship with two fields). I'm gonna fix this case too. Please, test the case initially reported too

**Comment by nollymar** [comment]
Fixed the case reported by @bryanboza . PR: https://github.com/dotCMS/core/pull/17531

**Comment by dsilvam** [comment]
Passed Internal QA Release: one self-relationship with two fields showing expected content from UI and from REST

**Comment by bryanboza** [comment]
Fixed, tested on the release branch with the provided bundle and now both cases work as expected

**Comment by wezell** [comment]
This is still broken when calling self joined relationships (relationshipField) in velocity and in graphql - the screenshot below was taken in master against the new starter - there should only be children:

![Screen Shot 2019-10-31 at 12 54 25 PM](https://user-images.githubusercontent.com/934364/67968459-d0be7e00-fbdd-11e9-897c-b3297bc377e2.png)

**Comment by nollymar** [comment]
@wezell I have fixed that issue on this PR: https://github.com/dotCMS/core/pull/17563

**Comment by wezell** [comment]
PR: #17563

**Comment by dsilvam** [comment]
Passed Internal QA Release: Returning the expected related content for both fields (Parent and Child) from both 1. GraphQL and 2. Velocity

**Comment by bryanboza** [comment]
Fixed, tested on the release branch calling from velocity and also with graphQL and now this works as expected

**Comment by erickgonzalez** [comment]
Tested on master and GraphQL, velocity and Rest returning the expected related content.

**Comment by bryanboza** [comment]
Fixed, tested on master too and works as expected
