### ISSUE TITLE
When change the page template the contents are gone

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18607]
### Describe the bug
When change the template in a page by another with the same container the content are gone.
Just happened to template create in the old template manager

### Steps to reproduce the behavior:
1. Create a new Template and add a Container
2. Create another new Template and add the same container
3. Create a pege with the template created in the first step
4. Add a content into the page
5. Change the page's template by the created in the second step

The reason why the contents are gone is that the UUID is not a correlative number then the container in the template has differnet UUID
### Expected behavior
Should keep the content because the template have the same container

### Screenshots

https://www.screencast.com/users/FreddyRodriguez/folders/Default/media/fb137d2a-7ab2-405b-872f-44093281e592

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We need some work here:

If create the template using the template designer and now from the layout of the page, we are not reflecting the changes here, the uuid still being the same that before
![image](https://user-images.githubusercontent.com/2641437/88343081-d032be00-ccfd-11ea-9279-cf93addf69ee.png)

We have another weird behavior here, that we need to take look, if using this template you add the same content to the 3 containers in the slide-bar, and then try yo publish the page, we are loosing the content of those containers
SC: https://www.screencast.com/t/Exk6WPCxzF

**Comment by dsilvam** [comment]
Fixed in PR: https://github.com/dotCMS/core/pull/19122

**Comment by dsilvam** [comment]
Passed Internal QA: Followed steps from description and also checked issues found by @bryanboza. All passing.

**Comment by bryanboza** [comment]
We still having problems here: 
- If you you create a template with a slide bar, and add the same container on this bar and also in the content side, and then try to add a piece of content to one of those, we are mixing the containers and we get a duplicated content 
SC: https://www.screencast.com/t/BxiGxJrA

**Comment by dsilvam** [comment]
Passed Internal QA: Case failing above passing.

**Comment by bryanboza** [comment]
We are getting the same error here: https://www.screencast.com/t/fESl8crn8

**Comment by dsilvam** [comment]
Passed Internal QA: Last bad behavior reported is now fixed.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF
