### ISSUE TITLE
Can't add link in WYSIWYG editor

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#19041]
When you try to add a link in the WYSIWYG editor you get a javascript error:

![image](https://user-images.githubusercontent.com/2195163/89526101-852da600-d7e7-11ea-82fb-d1f853210316.png)

This is with and without the tinymceprops setting. I was able to reproduce this locally in 5.3.3 and on the demo site in 5.3.5 using Chrome and Firefox on Windows. It still works on 5.1.6.

**To Reproduce**
1. Log in on the demo site
2. Go to content
3. Select Rich Text and open any content
4. Switch the body view to WYSIWYG
5. Click on "Insert / Edit link"
6. Click on the small browse button
7. Select a page, for instance Home on demo.dotcms.com
Now nothing happens since there is a javascript error.

**Expected behavior**
I would expect to see a link in the WYSIWYG editor

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postgres // FF

**Comment by Xander-Steinmann** [comment]
I tested the above code in a tinymceprops field and the file browser pops up now. There is still a problem with the url though:
Image: /shared-images/templates/base template thumbnail.pngbase template thumbnail.png
File: /version.txtversion.txt
Page: undefined

**Comment by Xander-Steinmann** [comment]
[tinymceprops-with-modified-cmsbrowser.txt](https://github.com/dotCMS/core/files/5061297/tinymceprops-with-modified-cmsbrowser.txt)

**Comment by fmontes** [comment]
@Xander-Steinmann checking this.
