### ISSUE TITLE
GraphQL Page API - Introduce ability to fire rules on render

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19219]
Just like the REST Page API supports, we need the ability to fire rules on the GraphQL Page API. 

A `fireRules` parameter at `page` field level is needed. 

E.g. 

```
{
  page(url: "/destinations/costa-rica", pageMode: "preview_mode", languageId: "1", fireRules: false) {
    title
    viewAs {
      persona {
        name
      }
    }
  }
}

```

**Comment by dsilvam** [comment]
Note to QA: Postman test included. The test checks that a certain rule was either triggered or not based on the value of the new parameeter `fireRules`

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19271

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF

**Comment by wezell** [comment]
Needs work:

- url maps do not seem to work - either when firing on every request or when you add them to the detail page.
- Setting the persona in the query does not seem to work, I still get persona=null
- Also, it does not seem like we are accruing tags?  A visitor should accrue tags when they hit a detail page with tags in it.

```
{
  page(url: "/store/products/eagles-nest-outfitters-doublenest-hammock-patriot", fireRules:true, persona:"EcoEnthusiast") {
    viewAs{
      visitor{
        persona{
          keyTag
        }
        geo{
          continent
          country
          latitude
          longitude
        }
        tags{
          tag
        }
      }
    }
  }  
}
```
