### ISSUE TITLE
Task Detail does not render in latest code

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19598]
From the workflow portlet, click on any task to be taken to the task detail.  You will get a jsp error.

This happens in master and in release-20.11

**Comment by nollymar** [comment]
Fixed: https://github.com/dotCMS/core/pull/19607

**Comment by nollymar** [comment]
**Note to QA:** Please test with locked/unlocked content

**Comment by bryanboza** [comment]
This still happening for the "Ecotourism in Costa Rica" content.. Tested with other pieces and works fine, we need to reach about what special have this piece of content

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes
