### ISSUE TITLE
We are not redirecting properly when the session expires 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19772]
When you leave an active session for a while and this expire, we invalidate the sessions and should redirect to the logout, but when this is happening we are just showing a blank page with a 404 error. 
![image](https://user-images.githubusercontent.com/2641437/103914738-e972cf80-50cf-11eb-9184-d803450cab9f.png)

FYI: You need to refresh the page to see the logout message. 

**Expected behavior**
Need redirect to the logout and then to the login again 

**Desktop (please complete the following information):**
Tested on release-21.01 // Postgres // FF and Chrome

**Comment by fmontes** [comment]
You can change the expire time here: https://github.com/dotCMS/core/blob/release-21.02/dotCMS/src/main/webapp/WEB-INF/web.xml#L542

**Comment by hmoreras** [comment]
adding timestamp to the `/dotAdmin/logout` PR: https://github.com/dotCMS/core-web/pull/1570

**Comment by erickgonzalez** [comment]
Fixed in #19902

**Comment by bryanboza** [comment]
Still getting a 404 error and a blank page when the session expires. Tested on release-21.03 // Postgres // Safari

**Comment by freddyucv** [comment]
it is solve here https://github.com/dotCMS/core/pull/20016

**Comment by victoralfaro-dotcms** [comment]
![image](https://user-images.githubusercontent.com/64026161/109845960-49d74680-7c13-11eb-9e71-09179d4461b7.png)
![image](https://user-images.githubusercontent.com/64026161/109846344-b4888200-7c13-11eb-9d95-10082c13b52d.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core-web/pull/1610

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/20037

**Comment by victoralfaro-dotcms** [comment]
Screenshot with time:
![image](https://user-images.githubusercontent.com/64026161/110386783-58b06580-8026-11eb-8116-6bfe7d32c0af.png)

**Comment by victoralfaro-dotcms** [comment]
Sign in at 16:18:22
![image](https://user-images.githubusercontent.com/64026161/110389322-f9545480-8029-11eb-9e65-e60ebb798c19.png)

Logout after two minutes as I set that in the web.xml
![image](https://user-images.githubusercontent.com/64026161/110389672-75e73300-802a-11eb-81d1-261f5f918294.png)

**Comment by bryanboza** [comment]
Fixed, tested on release 21.03 // Postgres // FF
