### ISSUE TITLE
Generating resource link for File Asset with Legacy Identifier is failing

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20597]
Reported via Support: [104564](https://dotcms.zendesk.com/agent/tickets/104564)
Reproducible in dotCMS 5.3.8.4, and latest master (21.05.1)

Customers coming from very old versions of dotCMS can have Contentlets or File Assets whose Identifier **IS NOT** a UUID, but a simple consecutive number. Such File Assets are presenting problems when opening them in the dotCMS back-end as there seems to be code that is expecting such Identifier to be a UUID, and not a number value with a character length lower than the default 10 characters.

**To Reproduce**
Please reach out to me in order to get further details on how to reproduce this.

**Expected behavior**
dotCMS must handle both new and Legacy Identifiers correctly.

**Additional context**
The code changes to fix this problem need to be based on the existing `dotshortyapi_use_legacy` property that allows dotCMS to deal with Legacy Identifiers at the API level.

**Comment by fabrizzio-dotCMS** [comment]
I was able to locate all the assets on the customer's database that still had a numeric identifier by using a custom function (isnumeric). 
The original issue was that the legacy ids were preventing the page from rendering. That has been solved no problem there. 
Now the page render and links are visible.
However, the file link presented in the dialog fails to load the asset. It gives you a 404
![Screen Shot 2021-08-04 at 14 33 55](https://user-images.githubusercontent.com/37148755/128253318-f92f202a-46a3-4f79-b856-ac9588b614f9.png)

And the reason is The system fails to build the link using a shorty therefore the identifier is used instead. Resulting in a non-valid link. Not sure how we want to proceed here. @wezell

**Comment by wezell** [comment]
@fabrizzio-dotCMS does the link still fail if you add `dotshortyapi_use_legacy` is set to true?

**Comment by fabrizzio-dotCMS** [comment]
@wezell as far as I recall the flag was set to true when I tested `dotshortyapi_use_legacy` but let me confirm real quick.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Docker
