### ISSUE TITLE
Add a ability to copy a content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21789]
**Is your feature request related to a problem? Please describe.**
When users are creating content types in a new instance a lot of time the content types shared common fields, like title, image, body, but the users have to create all those over and over again.

**Describe the solution you'd like**
We can allow the users to clone a content type, so it can reuse as many fields and settings they want.

**Describe alternatives you've considered**
N/A

**Additional context**
- [Figma File](https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=2306%3A33354)
- [Figma Prototype](https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?page-id=2306%3A33354&node-id=2316%3A33407&viewport=383%2C48%2C0.38&scaling=min-zoom&starting-point-node-id=2306%3A33358)

**Endpoint Information**
https://github.com/dotCMS/core/issues/21697#issuecomment-1044695817

**Comment by bryanboza** [comment]
We need some work here: 
- We are not resolving the key
![image](https://user-images.githubusercontent.com/2641437/161646030-679386a8-c63c-449c-adb1-854169568769.png)

![image](https://user-images.githubusercontent.com/2641437/161646087-011180b0-d860-453c-b2ed-e4d8bddba226.png)

**Comment by oidacra** [comment]
All the messages were added in this PR https://github.com/dotCMS/core/pull/21954/files

**Comment by fmontes** [comment]
Please try again it might be a timing issue with the docker image generation, I can see it in the branch.

**Comment by oidacra** [comment]
Probado localmente con Core (release-22.04) y Core-web (release-22.04)

**Menu**
![Screen Shot 2022-04-06 at 1 47 30 PM](https://user-images.githubusercontent.com/1909643/162047021-ef67a28b-f830-4bdb-879e-c999c7b72bfc.png)
 
**Dialog**
![Screen Shot 2022-04-06 at 1 47 35 PM](https://user-images.githubusercontent.com/1909643/162047033-38f3e113-06f4-4713-8a87-f28be5c5107f.png)

**Core**
![Screen Shot 2022-04-06 at 1 50 44 PM](https://user-images.githubusercontent.com/1909643/162047268-d39a513c-9c49-4f65-a38b-e8a4a0e96bd5.png)

**Core-Web**
![Screen Shot 2022-04-06 at 1 50 30 PM](https://user-images.githubusercontent.com/1909643/162047287-585c0532-8126-4630-91dc-bdade9f72d48.png)

**Comment by fmontes** [comment]
Failing on press enter

https://user-images.githubusercontent.com/751424/162070270-150947de-7c26-4813-8071-47402bd71709.mp4

**Comment by oidacra** [comment]
Fixed by https://github.com/dotCMS/core-web/pull/1943

**Comment by bryanboza** [comment]
We need some work here, tested with the last image of docker and when you are trying to create a copy a content type hit the enter key, we are getting this error:
![image](https://user-images.githubusercontent.com/2641437/163042429-9115bf03-8232-4e07-8f5f-aff7dc941e96.png)

**Comment by fmontes** [comment]
The sort order fields issues has been fixed.

**Comment by bryanboza** [comment]
We still getting the same error when you hit enter doing a copy from UI

**Comment by fmontes** [comment]
Fix merged, needs to test this specifically in Docker.

**Comment by fmontes** [comment]
Tested with this docker image dotcms/dotcms:22.04_810ed86_SNAPSHOT

Tested with hosts and files.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF. New card related was reported here:  #22104
