### ISSUE TITLE
Related content and default language

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#2322]
See https://groups.google.com/d/msg/dotcms/kf3pY5zFDNM/GttZVH5JvlEJ

Given the following conditions:
1. Two structures have a relationship; one ("A") has content in both languages and the other ("B") only has content in the default language
2. DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE is true

Then whenever we use pullRelated to obtain content of type B, we should obtain the content that exists, in the default language.  Currently we obtain nothing.

**Comment by mattyarbrough** [comment]
This continues to be an issue and is affecting customers in production

**Comment by wezell** [comment]
@mattyarbrough please specify a version - is this true on the latest release?

**Comment by mattyarbrough** [comment]
This is on 5.0.3, it's possible in 5.1+ to workaround with a condition parameter in the relationship

**Comment by wezell** [comment]
I believe this is fixed in 5.2 - @erickgonzalez can you confirm?

**Comment by erickgonzalez** [comment]
This is still an issue via ContentTool (velocity) but using the ContentResource it's working as it should, e.g. `http://localhost:8080/api/content/render/false/depth/1/query/+identifier:2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6 +languageId:2` pulls the parent content in Spanish and the relationship field shows the English since there is no version in Spanish.
