### ISSUE TITLE
Show proper message when Scheduling an Experiment

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24752]
### Parent Issue

#24343

### Problem Statement

When an Experiment with a valid Schedule is Scheduled an incorrect message is shown: 

Experiment started
Experiment "e4" started successfully

It should show:

Experiment scheduled
Experiment "e4" scheduled successfully

### Steps to Reproduce

1. Create a new Experiment
2. Add a Variant and set a Goal
3. Fill a valid Scheduling 
4. Schedule the Experiment

A notification with the incorrect message will be shown. 

### Acceptance Criteria

Show the expected message in the confirmation popup.

### dotCMS Version

23.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by oidacra** [comment]
Already fixed in master
![Screenshot 2023-04-26 at 11 32 23 AM](https://user-images.githubusercontent.com/1909643/234628072-9ac9d519-a765-4516-8a05-aabb437de61f.png)

**Comment by dsilvam** [comment]
Needs work. Still showing wrong message for Scheduled Experiments. This is when clicking "Schedule Experiments" instead of run

**Comment by oidacra** [comment]
https://github.com/dotCMS/core/pull/24913

**Comment by dsilvam** [comment]
Passed Internal QA. Showing proper message when Scheduling an Experiment. 

![Image](https://github.com/dotCMS/core/assets/1576794/fc2296d2-38ef-4c60-a122-ad2009030f1a)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. 

The shown message are the same ones in the provided images
