### ISSUE TITLE
Error when creating a new user if name, last name, or email fields exceed 100 characters.

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#27725]
### Problem Statement

![image](https://github.com/dotCMS/core/assets/127987858/c9e0c6b5-24eb-40a1-8280-68a9ee2e67b1)

`Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.5.1.jar:42.5.1]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.5.1.jar:42.5.1]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.5.1.jar:42.5.1]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql-42.5.1.jar:42.5.1]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql-42.5.1.jar:42.5.1]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.5.1.jar:42.5.1]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177) ~[postgresql-42.5.1.jar:42.5.1]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:676) ~[classes/:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:599) ~[classes/:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:307) ~[classes/:?]
	... 94 more`

### Steps to Reproduce

1- Create a new user
2- Add more than 100 characters in any of the following fields: First Name, Last Name, or email
3- Get SQL log error

### Acceptance Criteria

Sql errors should not be visible to the user. 
Add limit validation in the back-end (API). Additionally, we should catch the error and display a clear log error message.

### dotCMS Version

Master

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
The SQL error has been fixed and it no longer appears. Additionally, the error message is now very clear and easy to understand.

![Screenshot 2024-04-19 at 11 13 49 AM](https://github.com/dotCMS/core/assets/5278970/6542cd55-dbd6-4b8d-a1cc-14ba18015ab1)

**Comment by bryanboza** [comment]
We need some work here: 

- Now we have the validation for those fields, but we still having the same problems with the `middleName, nickName, birthday` field 
![Image](https://github.com/dotCMS/core/assets/2641437/a66ba4de-38f0-4cbb-87ff-a4943ae8c9c6)

- We need add postman test to verify this validations in every field

**Comment by dsolistorres** [comment]
Internal QA approved:
The middleName, nickName, and birthday fields are now validated with the 100 character limit

**Comment by bryanboza** [comment]
Problems to import the postman collection 

![Image](https://github.com/dotCMS/core/assets/2641437/179b10c9-3a8c-47df-86db-3296f7f2eb70)

Need to check the correct format...

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
