### ISSUE TITLE
UVE: You can't edit content thats been added to page and isn't showing anything

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#30068]
### Problem Statement

In UVE you can't edit content that has been added to a page but doesn't show anything. So if you add a widget that doesn't return a result you can't tell that it is on the page and you can't edit it from UVE.

### Steps to Reproduce

1.  Add a new widget to a page
2. Only give it a title and save it
3. Result is nothing even though the widget is on the page. You have no visual or ability to edit it

https://www.loom.com/share/7741a7ae822f4c2cba610792adb20a51?sid=e3dfa39a-78f2-493f-a730-6dd8cf7d40c4

### Acceptance Criteria

We should show a place holder or something letting the user know its on the page and giving them the ability to edit it

### dotCMS Version

current

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.loom.com/share/7741a7ae822f4c2cba610792adb20a51?sid=e3dfa39a-78f2-493f-a730-6dd8cf7d40c4

**Comment by fmontes** [comment]
We fixed that here, for traditional: https://github.com/dotCMS/core/issues/28377

**Comment by KevinDavilaDotCMS** [comment]
# Notes to QA

1. Create a ContentType
2. Create a Component in NextJs application for this ContentType, and render null or HTML with empty code,
like this
<img width="346" alt="Screenshot 2024-09-25 at 6 01 32 PM" src="https://github.com/user-attachments/assets/03e5b5cb-1d73-4581-8995-7017827b6095">

3. Go to UVE and check if the component is rendered with a min-height and you can edit it

**Comment by valentinogiardino** [comment]
### IQA FAILED

- Tested on latest trunk `trunk_ec4a905 ` - Chrome
- Followed the steps provided in the QA note using the Next.js example
- Still unable to edit contentlets with empty HTML content

#### Video
https://github.com/user-attachments/assets/9dd94311-f879-4ede-8030-47474882faf9

**Comment by valentinogiardino** [comment]
### IQA PASSED

- Tested using `dotcms/dotcms:trunk_0028f3c` &`@dotcms/react: "latest"` (0.0.1-alpha.41)
- Now users can edit contentlets with empty HTML content in UVE

#### Screenshot
<img width="1638" alt="image" src="https://github.com/user-attachments/assets/ace07c55-d0fd-4e98-95e2-cca8c3591419">

**Comment by bryanboza** [comment]
Fixed, now we are adding the blank space corresponding to the added content.

![Image](https://github.com/user-attachments/assets/322539b2-ce48-4688-a1ef-76fba319167a)
