### ISSUE TITLE
Push Publishing - NullPointerException when pushing from a sender to another reciver

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#9110]
The following exception was reported in the dotcms.log file when pushing from a sender to a receiver.

```
[18/05/16 10:28:20:327 EDT]  INFO util.FileUtil: Move method: Source equal to Destination, no need to move.
[18/05/16 10:28:20:388 EDT]  INFO util.FileUtil: Move method: Source equal to Destination, no need to move.
[18/05/16 10:28:21:745 EDT] ERROR handler.RuleHandler: An error occurred when processing rule [0862904c-105d-4d8d-8991-e7ec34b132ae] in bundle [fc2811ad-857c-451f-a94e-4594a5859885.tar.gz]
java.lang.NullPointerException: Rule is required
    at com.dotcms.repackage.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204) ~[dot.guava-11.0.1_2.jar:?]
    at com.dotmarketing.portlets.rules.business.RulesCacheImpl.getConditionGroupsIdsByRule(RulesCacheImpl.java:294) ~[dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.enterprise.rules.h.getConditionGroupsByRule(SourceFile:310) ~[ee-gaf7f4f0.jar:?]
    at com.dotcms.enterprise.RulesFactoryProxy.getConditionGroupsByRule(SourceFile:126) ~[ee-gaf7f4f0.jar:?]
    at com.dotmarketing.portlets.rules.model.Rule.getGroups(Rule.java:179) ~[dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.a(SourceFile:122) [ee-gaf7f4f0.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.handle(SourceFile:74) [ee-gaf7f4f0.jar:?]
    at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161) [dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_3.5_g14af2ce.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[18/05/16 10:28:21:752 EDT]  INFO guava.GuavaCache: ***  Building Cache : workflowstepcache, size:1000,Concurrency:32
[18/05/16 10:28:21:841 EDT] ERROR business.PublisherAPIImpl: Error Publishing Bundle: An error occurred when processing rule [0862904c-105d-4d8d-8991-e7ec34b132ae] in bundle [fc2811ad-857c-451f-a94e-4594a5859885.tar.gz]
com.dotcms.publishing.DotPublishingException: An error occurred when processing rule [0862904c-105d-4d8d-8991-e7ec34b132ae] in bundle [fc2811ad-857c-451f-a94e-4594a5859885.tar.gz]
    at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.a(SourceFile:166) ~[ee-gaf7f4f0.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.handle(SourceFile:74) ~[ee-gaf7f4f0.jar:?]
    at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161) [dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_3.5_g14af2ce.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException: Rule is required
    at com.dotcms.repackage.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204) ~[dot.guava-11.0.1_2.jar:?]
    at com.dotmarketing.portlets.rules.business.RulesCacheImpl.getConditionGroupsIdsByRule(RulesCacheImpl.java:294) ~[dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.enterprise.rules.h.getConditionGroupsByRule(SourceFile:310) ~[ee-gaf7f4f0.jar:?]
    at com.dotcms.enterprise.RulesFactoryProxy.getConditionGroupsByRule(SourceFile:126) ~[ee-gaf7f4f0.jar:?]
    at com.dotmarketing.portlets.rules.model.Rule.getGroups(Rule.java:179) ~[dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.a(SourceFile:122) ~[ee-gaf7f4f0.jar:?]
    ... 4 more
[18/05/16 10:28:21:845 EDT] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: An error occurred when processing rule [0862904c-105d-4d8d-8991-e7ec34b132ae] in bundle [fc2811ad-857c-451f-a94e-4594a5859885.tar.gz]
[18/05/16 10:28:21:845 EDT]  INFO rest.PublishThread: Finished bundle publish process
```

Both sender and receiver were running the dotCMS 3.5 starter site.

To reproduce:
1. Create a new host (empty on the sender side, for example: pushpublishingtest.dotcmscloud.com)
2. Create a new page using a starter site template (for example: pushpublishingtest.dotcmscloud.com/pp-test using "demo.dotcms.com Quest - 1 Column")
3. Add a Content(Generic) piece of content to that page
4. Push the whole host to the receiver
5. You'll get the `Rule is required` error in the log.

**Comment by erickgonzalez** [comment]
Not able to reproduce in 3.6.

Tried with one single instance (as sender and receiver) and with a two-node cluster (as sender and receiver).

**Comment by oarrietadotcms** [comment]
We need to reopen this one: 

Cloud clients in 4.x experiencing the same error: 

1. https://dotcms.zendesk.com/agent/tickets/96686
2. https://dotcms.zendesk.com/agent/tickets/96761

Can't reproduce locally so we will clone a an instance and remote debug.

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/15846
https://github.com/dotCMS/enterprise-2.x/pull/652

**Comment by bryanboza** [comment]
Fixed, tested after the fix and now I'm unable to recreate the instance locally. Tested with the following environments: 

Sender: MacOSX // master // Oracle // FF 
Receiver: MacOSX // master // postgres // Safari

**Comment by oarrietadotcms** [comment]
hi team, this is still failing in our latest release: 5.1.5

I found an easy way to reproduce:

1. Set up a PP with 2 vanilla dotCMS's. 

2. In the receiver set up a Rule like this:

<img width="1188" alt="Screen Shot 2019-05-30 at 7 40 57 PM" src="https://user-images.githubusercontent.com/8225685/58678569-68612d00-831d-11e9-9a59-60f9f07d6606.png">

3. Push the whole Demo Site to the receiver.

4. Check that the first push was fine. 

5. Let's emulate some load in the receiver: you can use Apache Benchmark. For example: `ab -n 100000 -c 3 http://<RECEIVER-IP>:<PORT>/`

6. Push the whole site again, using Force Push. 

7. You will see an error like this:

```
20:52:00.209  INFO  caffine.CaffineCache - ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
20:52:00.818  INFO  caffine.CaffineCache - ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
20:52:00.866  ERROR business.PublisherAPIImpl - Error publishing bundle with ID '07ad9d5f-83cc-4c60-840e-ebefd35a600d.tar.gz': An error occurred when processing rule [349a3bf0-7526-471c-8c22-08c989871ada] in bundle [07ad9d5f-83cc-4c60-840e-ebefd35a600d.tar.gz]
com.dotcms.publishing.DotPublishingException: An error occurred when processing rule [349a3bf0-7526-471c-8c22-08c989871ada] in bundle [07ad9d5f-83cc-4c60-840e-ebefd35a600d.tar.gz]
	at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.handleRules(RuleHandler.java:180) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.handle(RuleHandler.java:82) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.1.5_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.1.5_999999.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException: Rule is required
	at com.dotcms.repackage.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204) ~[dot.guava-11.0.1_2.jar:?]
	at com.dotmarketing.portlets.rules.business.RulesCacheImpl.getActionsIdsByRule(RulesCacheImpl.java:371) ~[dotcms_5.1.5_999999.jar:?]
	at com.dotcms.enterprise.rules.RulesFactoryImpl.getRuleActionsByRule(RulesFactoryImpl.java:177) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.RulesFactoryProxy.getRuleActionsByRule(RulesFactoryProxy.java:104) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.rules.RulesAPIImpl.deleteRuleActionsByRule(RulesAPIImpl.java:353) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.RulesAPIProxy.deleteRuleActionsByRule(RulesAPIProxy.java:387) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.publishRule(RuleHandler.java:198) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.RuleHandler.handleRules(RuleHandler.java:150) ~[ee_clean.jar:?]
	... 4 more
20:52:00.875  ERROR lang.String - Error publishing bundle with ID '07ad9d5f-83cc-4c60-840e-ebefd35a600d.tar.gz': com.dotcms.publishing.DotPublishingException: An error occurred when processing rule [349a3bf0-7526-471c-8c22-08c989871ada] in bundle [07ad9d5f-83cc-4c60-840e-ebefd35a600d.tar.gz]
20:52:00.875  INFO  util.PushPublishLogger - class com.dotcms.rest.PublishThread : [BundleID: 07ad9d5f-83cc-4c60-840e-ebefd35a600d.tar.gz] Finished bundle publish process
20:52:00.875  INFO  rest.PublishThread - Finished bundle publish process
```

**Comment by wezell** [comment]
Great update @oarrietadotcms, we will take a look
